// Code generated by "stringer -type=Value"; DO NOT EDIT.

package main

import "strconv"

const _Value_name = "acetwothreefourfivesixseveneightninejackqueenking"

var _Value_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 40, 45, 49}

func (i Value) String() string {
	if i < 0 || i >= Value(len(_Value_index)-1) {
		return "Value(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Value_name[_Value_index[i]:_Value_index[i+1]]
}
